# SPDX-License-Identifier: MPL-2.0
execute_process(COMMAND "${FIXTURES}" "${DIRECTORY}" RESULT_VARIABLE fixture_result
    OUTPUT_VARIABLE fixture_output ERROR_VARIABLE fixture_error TIMEOUT 30)
if(NOT fixture_result EQUAL 0)
    message(FATAL_ERROR "Fixture setup failed: ${fixture_output} ${fixture_error}")
endif()
function(invoke expected pattern)
    execute_process(COMMAND "${INSPECTOR}" ${ARGN} RESULT_VARIABLE result
        OUTPUT_VARIABLE report ERROR_VARIABLE errors TIMEOUT 10)
    if(NOT "${result}" STREQUAL "${expected}" OR NOT "${report}" MATCHES "${pattern}" OR errors)
        message(FATAL_ERROR "CLI result ${result}, expected ${expected}, pattern ${pattern}: ${report} ${errors}")
    endif()
endfunction()
invoke(0 "usage:" --help)
invoke(2 "usage:")
invoke(2 "usage:" --nav)
invoke(2 "usage:" --nav "${DIRECTORY}/v5.nav" --profile unknown)
invoke(2 "usage:" --nav "${DIRECTORY}/v5.nav" --nav "${DIRECTORY}/v1.nav")
invoke(2 "stage=cli" --nav "${DIRECTORY}/v5.nav" --unknown)
invoke(2 "usage:" --nav "${DIRECTORY}/v5.nav" --start 1 1 0)
invoke(2 "usage:" --nav "${DIRECTORY}/v5.nav" --radius 1)
invoke(2 "usage:" --nav "${DIRECTORY}/v5.nav" --start 1 1 0 --goal 4 1 4 --radius 10)
foreach(invalid IN ITEMS nan inf 1e999 2junk -1)
    invoke(2 "usage:" --nav "${DIRECTORY}/v5.nav" --start 1 1 0 --goal 4 1 4 --radius "${invalid}" --vertical 10)
endforeach()
invoke(2 "usage:" --nav "${DIRECTORY}/v5.nav" --start 1e39 1 0 --goal 4 1 4 --radius 10 --vertical 10)
invoke(2 "usage:" --nav "${DIRECTORY}/v5.nav" --start 1 1 0 --goal 4 1 4 --radius 10 --vertical nan)
invoke(1 "stage=input" --nav "${DIRECTORY}/does-not-exist.nav")
invoke(1 "stage=input" --nav "${DIRECTORY}")
invoke(1 "stage=bsp" --nav "${DIRECTORY}/v5.nav" --bsp "${DIRECTORY}/missing.bsp")
invoke(1 "stage=bsp" --nav "${DIRECTORY}/v5.nav" --bsp "${DIRECTORY}/sample.bsp")
invoke(0 "bsp_size_comparison=AbsentInVersion" --nav "${DIRECTORY}/v1.nav" --bsp "${DIRECTORY}/sample.bsp")
foreach(version RANGE 1 5)
    file(SHA256 "${DIRECTORY}/v${version}.nav" before)
    invoke(0 "version=${version}" --nav "${DIRECTORY}/v${version}.nav" --profile compatibility-v1)
    file(SHA256 "${DIRECTORY}/v${version}.nav" after)
    if(NOT before STREQUAL after)
        message(FATAL_ERROR "Input changed")
    endif()
endforeach()
invoke(0 "route_status=Complete" --nav "${DIRECTORY}/directed.nav" --start 1 1 0 --goal 4 1 4 --radius 10 --vertical 10)
invoke(0 "route_status=Unreachable" --nav "${DIRECTORY}/directed.nav" --start 4 1 4 --goal 1 1 0 --radius 10 --vertical 10)
invoke(0 "start_method=nearestGeometry" --nav "${DIRECTORY}/v5.nav" --start -1 1 0 --goal 4 1 4 --radius 10 --vertical 10)
invoke(1 "start_match=None" --nav "${DIRECTORY}/v5.nav" --start -1 1 0 --goal 4 1 4 --radius 0 --vertical 0)
